In [1]:
import pandas as pd, numpy as np
import matplotlib.pyplot as plt, seaborn as sns
%matplotlib inline

In [2]:
import os
os.getcwd()

'c:\\Users\\harleyquinn\\Documents\\GitHub\\Bollywood_movie_analysis\\final\\text'

In [3]:
os.chdir("C:\\Users\\harleyquinn\\Documents\\GitHub\\Bollywood_movie_analysis\\final\\analysis")

In [7]:
df= pd.read_csv('C:\\Users\\harleyquinn\\Documents\\GitHub\\Bollywood_movie_analysis\\final\\text\\gender.csv')  
df

    Unnamed: 0                                               Name  Gender
0            0  Arun, Neelakandan, A, Teenager, From, Kerala, ...    male
1            1  Love, College, Sweetheart, Darshana, First, Sight    male
2            2  Arun, Is, A, Few, Scuffles, Incidents, Seniors...    male
3            3  Arun, Friend, Antony, Online, Girlfriend, Feel...    male
4            4        Her, States, Single, A, Kiss, Moral, Police    male
5            5  Arun, Darshana, Who, Lividly, Calls, Relationship    male
6            6                        Heat, Their, Argument, Than    male
7            7                Arun, Life, Goes, Downhill, Breakup    male
8            8                        Year, Is, Addicted, Alcohol  female
9            9   Relationship, Maya, DoesnT, Find, Himself, Happy    male
10          10      Darshana, Starts, Dating, Kedar, A, Womanizer    male
11          11                        Darshana, A, Sign, Jealousy  female
12          12    Arun, Is, Proven, Right, Darshana, Slaps, Kedar    male
13          13  Kedar, Threatens, Rumours, Her, Friend, Convey...    male
14          14  Home, Arun, Parents, Notice, Something, Their,...    male
15          15  Father, Him, Quit, Alcohol, Turn, Over, A, New...    male
16          16  Arun, Out, Shared, Hostel, Room, A, More, Peac...  female
17          17  Classmate, Selva, Coaching, Antony, Rebound, A...    male
18          18  Darshana, Too, Joins, Selva, Coaching, Class, ...    male
19          19  Selva, A, Bus, Accident, Everyone, Class, Grie...    male
20          20  Maya, Calls, Off, Relationship, Arun, Father, ...    male
21          21  Day, College, Led, Into, A, Room, Called, Secr...    male
22          22                    Arun, Himself, Unable, Anything    male
23          23  Darshana, Who, Arun, Train, Asks, Him, Been, T...    male
24          24                                             Answer    male
25          25        Graduation, Arun, Job, A, Campus, Interview    male
26          26                     Arun, Feels, Dissatisfied, Job    male
27          27            Darshana, Youtube, Vlogger, Him, Dreams    male
28          28  A, Bus, Journey, Jimmy, A, Wedding, Photograph...    male
29          29  Arun, Company, Intimate, Weddings, No, Such, B...  female
30          30  Company, Shoutout, Prateek, Tiwari, Batchmate,...    male
31          31   Shoutout, Lots, Bookings, Arun, Feels, Satisfied    male
32          32  Arun, Sees, Nithya, Balagopal, Feels, Instantl...    male
33          33  Photographs, Nithya, Recommends, Arun, Her, Co...    male
34          34  Arun, Discovers, Groom, Is, Kedar, Exposes, Ch...  female
35          35  Wedding, Is, Off, Nithya, Is, Grateful, Arun, ...    male
36          36  Closer, Nithya, Accompanies, Arun, Chennai, We...    male
37          37  Their, Parents, Approval, Nithya, Arun, Fix, T...    male
38          38  Darshana, Wedding, Reception, Finds, Herself, ...    male
39          39  Arun, Nithya, Get, Married, Live, Happily, The...    male
40          40                 Nithya, Gives, Birth, A, Baby, Boy    male
41          41        Arun, Feels, Telling, Darshana, News, First    male
42          42  Darshana, Marriage, Arun, Nitya, Along, Their,...  female
43          43                                Night, Place, Beach    male
44          44  Arun, Secretly, Leave, Nithya, Wakes, Up, Bach...    male
45          45  Arun, Feels, Guilty, Goes, Room, Nithya, A, Sa...    male
46          46                                     Meet, Darshana  female
47          47                             Him, Sleep, Peacefully    male
48          48  Darshana, Who, Due, Married, Next, Day, Expres...    male
49          49  Arun, Tells, Her, WhatIfs, Look, Forward, Her,...    male
50          50                            Darshana, Gets, Married    male
51          51  Chennai, Arun, Takes, A, Detour, Kc, Tech, Key...  female
52          52  Thank, College, Him, Campus, Where, Nithya, Th...    male

In [8]:
df.fillna("1", inplace = True)

In [9]:
df = df.dropna(axis=1)

print(df)

    Unnamed: 0                                               Name  Gender
0            0  Arun, Neelakandan, A, Teenager, From, Kerala, ...    male
1            1  Love, College, Sweetheart, Darshana, First, Sight    male
2            2  Arun, Is, A, Few, Scuffles, Incidents, Seniors...    male
3            3  Arun, Friend, Antony, Online, Girlfriend, Feel...    male
4            4        Her, States, Single, A, Kiss, Moral, Police    male
5            5  Arun, Darshana, Who, Lividly, Calls, Relationship    male
6            6                        Heat, Their, Argument, Than    male
7            7                Arun, Life, Goes, Downhill, Breakup    male
8            8                        Year, Is, Addicted, Alcohol  female
9            9   Relationship, Maya, DoesnT, Find, Himself, Happy    male
10          10      Darshana, Starts, Dating, Kedar, A, Womanizer    male
11          11                        Darshana, A, Sign, Jealousy  female
12          12    Arun, Is, Proven, Right, Darshana, Slaps, Kedar    male
13          13  Kedar, Threatens, Rumours, Her, Friend, Convey...    male
14          14  Home, Arun, Parents, Notice, Something, Their,...    male
15          15  Father, Him, Quit, Alcohol, Turn, Over, A, New...    male
16          16  Arun, Out, Shared, Hostel, Room, A, More, Peac...  female
17          17  Classmate, Selva, Coaching, Antony, Rebound, A...    male
18          18  Darshana, Too, Joins, Selva, Coaching, Class, ...    male
19          19  Selva, A, Bus, Accident, Everyone, Class, Grie...    male
20          20  Maya, Calls, Off, Relationship, Arun, Father, ...    male
21          21  Day, College, Led, Into, A, Room, Called, Secr...    male
22          22                    Arun, Himself, Unable, Anything    male
23          23  Darshana, Who, Arun, Train, Asks, Him, Been, T...    male
24          24                                             Answer    male
25          25        Graduation, Arun, Job, A, Campus, Interview    male
26          26                     Arun, Feels, Dissatisfied, Job    male
27          27            Darshana, Youtube, Vlogger, Him, Dreams    male
28          28  A, Bus, Journey, Jimmy, A, Wedding, Photograph...    male
29          29  Arun, Company, Intimate, Weddings, No, Such, B...  female
30          30  Company, Shoutout, Prateek, Tiwari, Batchmate,...    male
31          31   Shoutout, Lots, Bookings, Arun, Feels, Satisfied    male
32          32  Arun, Sees, Nithya, Balagopal, Feels, Instantl...    male
33          33  Photographs, Nithya, Recommends, Arun, Her, Co...    male
34          34  Arun, Discovers, Groom, Is, Kedar, Exposes, Ch...  female
35          35  Wedding, Is, Off, Nithya, Is, Grateful, Arun, ...    male
36          36  Closer, Nithya, Accompanies, Arun, Chennai, We...    male
37          37  Their, Parents, Approval, Nithya, Arun, Fix, T...    male
38          38  Darshana, Wedding, Reception, Finds, Herself, ...    male
39          39  Arun, Nithya, Get, Married, Live, Happily, The...    male
40          40                 Nithya, Gives, Birth, A, Baby, Boy    male
41          41        Arun, Feels, Telling, Darshana, News, First    male
42          42  Darshana, Marriage, Arun, Nitya, Along, Their,...  female
43          43                                Night, Place, Beach    male
44          44  Arun, Secretly, Leave, Nithya, Wakes, Up, Bach...    male
45          45  Arun, Feels, Guilty, Goes, Room, Nithya, A, Sa...    male
46          46                                     Meet, Darshana  female
47          47                             Him, Sleep, Peacefully    male
48          48  Darshana, Who, Due, Married, Next, Day, Expres...    male
49          49  Arun, Tells, Her, WhatIfs, Look, Forward, Her,...    male
50          50                            Darshana, Gets, Married    male
51          51  Chennai, Arun, Takes, A, Detour, Kc, Tech, Key...  female
52          52  Thank, College, Him, Campus, Where, Nithya, Th...    male

In [10]:
df.isna().sum()

Unnamed: 0    0
Name          0
Gender        0
dtype: int64

In [11]:
df['Gender'] = np.where((df['Gender'] == 'male'), 1, 0)

In [12]:
df['Gender']

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     0
9     1
10    1
11    0
12    1
13    1
14    1
15    1
16    0
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    0
30    1
31    1
32    1
33    1
34    0
35    1
36    1
37    1
38    1
39    1
40    1
41    1
42    0
43    1
44    1
45    1
46    0
47    1
48    1
49    1
50    1
51    0
52    1
Name: Gender, dtype: int32

In [13]:
X=df.drop('Gender',axis=1)
y=df['Gender']

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [14]:
import category_encoders as ce

In [15]:
encoder = ce.OrdinalEncoder(cols=['Name'])


X_train = encoder.fit_transform(X_train)

X_test = encoder.transform(X_test)

In [16]:
X_train

    Unnamed: 0  Name
34          34     1
4            4     2
37          37     3
24          24     4
44          44     5
33          33     6
49          49     7
15          15     8
9            9     9
16          16    10
30          30    11
36          36    12
25          25    13
11          11    14
0            0    15
46          46    16
27          27    17
31          31    18
39          39    19
29          29    20
45          45    21
1            1    22
21          21    23
2            2    24
40          40    25
35          35    26
23          23    27
48          48    28
10          10    29
22          22    30
18          18    31
52          52    32
20          20    33
7            7    34
42          42    35
14          14    36
28          28    37
51          51    38
38          38    39

In [17]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(random_state = 0)
classifier.fit(X_train, Y_train)

RandomForestClassifier(random_state=0)

In [18]:
Y_pred = classifier.predict(X_test)

In [19]:
cutoff = 0.7                              
y_pred_classes = np.zeros_like(Y_pred)    
y_pred_classes[Y_pred > cutoff] = 1

In [20]:
y_test_classes = np.zeros_like(Y_pred)
y_test_classes[Y_test > cutoff] = 1

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test_classes, y_pred_classes)

print ("Confusion Matrix : \n", cm)

Confusion Matrix :
 [[0 1]
 [9 4]]

In [22]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test_classes, y_pred_classes))

Accuracy :  0.2857142857142857

In [23]:
complete_data="Accuracy : ", accuracy_score(y_test_classes, y_pred_classes)

In [24]:
complete_data

('Accuracy : ', 0.2857142857142857)